spring:
    main:
        allow-bean-definition-overriding: true

    datasource:
        url: jdbc:h2:file:~/h2db;AUTO_SERVER=true
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    h2:
        console:
            enabled: true
            path: /h2-console

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
